Check if search index out of bounds
James-LG/Skyscraper pull request #21
Opened 2023-12-12 12:01 UTC by masc-it

**Problem**

Let's assume I want to search for a **strong[1]**, with a parent node **//div**, but some of the divs don't have it. As the search is implemented right now, the [code](https://github.com/James-LG/Skyscraper/blob/master/src/xpath/search.rs#L151) will just panic, since it does not handle out of bound indexing.

**Solution**
Just add a simple check on the search index. I didn't fix it [deeper, at the DocumentNodeSet level](https://github.com/James-LG/Skyscraper/blob/master/src/xpath/mod.rs#L415), since raw indexing is heavily used in a lot of places and would require more effort.

2023-12-15 01:16 UTC, James-LG requested changes
Hi, thanks for your PR.

FYI the indexing in general is currently broken and requires much larger changes; it indexes based on the entire set of nodes, rather than for each parent node.

For example, applying `//node/div[1]` to the html below should return `<div>hello</div>` and `<div>world</div>` but actually only returns `<div>hello</div>`.

```html
<root>
    <node>
        <div>hello</div>
        <div>foo</div>
    </node>
    <node>
        <div>world</div>
        <div>bar</div>
    </node>
    <node>
        <p>not a div</p>
    </node>
</root>
```

I'm currently working on a full rewrite of the XPath side of the library since it was originally hacked together without regard for the official XPath specification as a "good enough" library for another project I had.

I'm putting my effort towards the rewrite (which is quite an undertaking) rather than fixing this code  https://github.com/James-LG/Skyscraper/compare/master...james/nom

Just to avoid the panic I'll accept these changes if you fix the off-by-one error and ensure if the index is greater than the matched nodes, none are returned rather than all.

2023-12-15 07:59 UTC, masc-it commented on src/xpath/search.rs
> +        }
Sorry for the delay, just got the notif by Github! New commit :)

2023-12-16 00:24 UTC, James-LG approved these changes

2023-12-16 00:25 UTC, merged

2023-12-16 00:28 UTC, James-LG commented
> BTW, I'll take a look to the new nom branch, happy to help if needed :)

I'd like to get the basic use-cases working first, so the structure is a bit more settled than it currently is, but after that support on things like the `contains` functions would be great! XPath is pretty huge so there's lots of parallel work once the basics are in place.

2023-12-16 07:58 UTC, masc-it commented
Clear! Do you have a roadmap in place? Or a discord channel to post updates?

2023-12-17 03:29 UTC, James-LG commented
Since GitHub apparently doesn't have direct messaging I created a brand new discord channel https://discord.gg/jWK42bWK

As for roadmap, I don't have anything formal. Vaguely it will be get basic steps working `/` and `//` (including initial occurrences which behave differently), then filtered expressions like `/div[@class='hi']`, and go from there.